auth:
  repository: auth-service
  tag: "v1"
  replicaCount: 1
  port: 5001

tasks:
  repository: task-service
  tag: "v1"
  replicaCount: 2
  port: 5002
  nodePort: 30002

mysql:
  image: mysql:8.0
  port: 3306
  storage: 1Gi
  rootPassword: "password"
  database: "tasks_db"

adminer:
  image: adminer:latest
  port: 8080
  nodePort: 30003

portainer:
  image: portainer/portainer-ce:latest
  port: 9000
  nodePort: 30004

metricsServer:
  enabled: true
  image: registry.k8s.io/metrics-server/metrics-server:v0.7.2
  replicas: 1
  args:
    - --cert-dir=/tmp
    - --secure-port=4443
    - --kubelet-insecure-tls
    - --kubelet-preferred-address-types=InternalIP,Hostname,ExternalIP
    - --kubelet-use-node-status-port
    - --metric-resolution=15s

monitoring:
  enabled: true
  grafanaPort: 30005